### PR TITLE
Add suport for Azure Pipelines

### LINKED ISSUE #50: Add support for Azure Pipelines
The tool does not currently automatically detect the build server variables from Azure Pipelines.

The variables are all documented here:
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

### PR DESCRIPTION
**Pull request by clairernovotny**
Fixes #50

### CODE REVIEW

**Comment by AdmiringWorm** [comment]
Thank you for opening a PR to implement this. I do not have the possibility to review the PR at this time, but hope to manage to review it tomorrow (at the latest friday).

**Comment by astrofrog** [comment]
Looking forward to this!

**Review by AdmiringWorm — APPROVED** [review]
LGTM. Thank you for your contribution.
I apologise for the long delay of me review this PR.

I'm currently preparing a new release, in which this feature will be among them.

**Comment by AdmiringWorm** [comment]
Your changes have been merged into the develop branch here: https://github.com/codecov/codecov-exe/commit/cb77bae0b5390cf10987a7c15dc19f59c75031c7

**Comment by AraHaan** [comment]
Is this merged into master yet? my version that I am installing manually from nuget.org on appveyor and azure pipelines seems to have a issue identifying this exact thing and I was just about to open a new issue that would be a duplicate of #50. If there is a newer nuget.org release mind editing my Appveyor and azure yml’s to fix the issue in my repo?

https://github.com/AraHaan/XmlAbstraction/

Edit: It is because I am using v1.1.0 but the latest is v1.4.0 maybe you guys should warn people if and when the tool discovers a new version from the github releases?

**Pull request closed without merging**
