### PR TITLE
GZip compress content for uploading

### PR DESCRIPTION
**Pull request by sharwell**
See codecov/codecov-bash@4120dfb969d69f64bc5fa7ccf1443cd4bf4d9a4a

📝 I don't have a good way to test that this works. If the pull request build from AppVeyor is available through the AppVeyor NuGet feed, I can update one of our projects to use this build as a verification step.

### CODE REVIEW

**Comment by sharwell** [comment]
I was finally able to experiment with this and it appears to be working for DotNetAnalyzers/StyleCopAnalyzers#2771. Unrelated network issues are making it difficult to test the larger scale project with dotnet/project-system#3942.

**Comment by stevepeak** [comment]
@larzw Thank's to @sharwell we can merge this pull and support `gzip` uploading. Great job @sharwell

**Comment by larzw** [comment]
nice job @sharwell!

/cc @AdmiringWorm

**Comment by AdmiringWorm** [comment]
@sharwell thank you for this, and sorry about not being able to respond earlier.

I'll try getting a new release out with these changes (as well as some other changes I have in a different branch) later this week.

**Comment by sharwell** [comment]
@AdmiringWorm Thanks! This is hard-blocking us for the past two weeks because our upload size without gzip exceeds the new limits for the service. We won't have code coverage features until the next release is available.

**Comment by AdmiringWorm** [comment]
@sharwell I see, I'll try making it a priority to get out a new release, unfortunately I won't be able to do that until Wednesday at the earliest.

**Comment by AdmiringWorm** [comment]
@sharwell I just pushed out a new version now to nuget. It's currently being validated, but should be available soon.

EDIT:
Chocolatey package will come at a later date, as they are currently experiencing website issues.

**Pull request merged**
