### PR TITLE
Add new Codecov.MSBuild package providing a `Codecov`MSBuild task

### PR DESCRIPTION
**Pull request by 0xced**
* Refactored the `UploadFacade` class to depend on interfaces instead of CommandLineOptions so that it's usable from the MSBuild task
* Added documentation in the README about the new `Codecov.MSBuild` package
* Updated Cake scripts to handle the new `Codecov.MSBuild` package

### CODE REVIEW

**Comment by 0xced** [comment]
I just rebased and fixed the continuous integration build in 3f937c1.

**Comment by 0xced** [comment]
I would love to see this merged. Currently I'm using the codecov dotnet tool and it's not as elegant as the proposed MSBuild task.

With the dotnet tool:

```xml
<Target Name="UploadCoverageToCodecov" AfterTargets="GenerateCoverageResultAfterTest" Condition="$(ContinuousIntegrationBuild) == 'true'">
  <!-- For reference: the file `.config/dotnet-tools.json` was created by running `dotnet new tool-manifest && dotnet tool install Codecov.Tool` -->
  <Exec Command="dotnet tool restore" />
  <Exec Command="dotnet codecov --file &quot;@(CoverletReport, '&quot; &quot;')&quot;" />
</Target>
```

With the proposed MSBuild task:

```xml
<Target Name="UploadCoverageToCodecov" AfterTargets="GenerateCoverageResultAfterTest" Condition="$(ContinuousIntegrationBuild) == 'true'">
  <Codecov ReportFiles="@(CoverletReport)" />
</Target>
```

Also, logging is top notch with the MSBuild task.

**Review by AdmiringWorm — APPROVED** [review]
LGTM, sorry about the delay to merge this PR

**Comment by AdmiringWorm** [comment]
@0xced your changes have been merged, thanks for your contribution 👍

I have decided that this change will be included with the next version of codecov-exe, just need to find time to be able to create a new release and check out all of the pr's to update the dependencies first.

**Comment by 0xced** [comment]
Excellent, thanks for merging! 🥳

No need to apologise for the delay, better work at a your own pace than experience open source burnout.

**Pull request merged**
