### PR TITLE
Add global tool

### PR DESCRIPTION
**Pull request by ViktorHofer**
Contributes to https://github.com/codecov/codecov-exe/issues/44

@AdmiringWorm You probably want to add this project to your CI. For now I suggest do a one-off package upload:

```
cd Source\Codecov\
dotnet pack /p:PackageVersion=1.0.0
```

Upload the generated NuGet package. The global tool can be advertised to be the preferred solution for all operating systems. The only requirement is an installed .NET Core SDK.

### CODE REVIEW

**Comment by ViktorHofer** [comment]
ping @AdmiringWorm

**Comment by ViktorHofer** [comment]
We would like to use the global tool in https://github.com/dotnet/corefx. Please let me know how I can help you to get this published on nuget. We are currently blocked by it as we can't use the self-contained application (file size).

**Comment by AdmiringWorm** [comment]
@ViktorHofer Your PR haven't gone unnoticed, unfortunately due to real life issue ATM I haven't yet had a chance to look over the PR and decide how to integrate it into the build process.

I do hope to have the chance to do exactly that in the next couple of days.

**Comment by ViktorHofer** [comment]
Great, thanks for letting me know

**Review by AdmiringWorm — APPROVED** [review]
LGTM, thank you for your contributions

**Comment by AdmiringWorm** [comment]
Your changed has been merged in the develop branch (this PR will most likely be closed automatically when I'm ready to do a new release).

The new tool will be pushed later today with some other changes I'm working on. (If everything works as expected when I'm done).

**Pull request merged**
